import './globals.css';
import NavBar from '@/app/layout/NavBar';
import CssBaseline from '@mui/material/CssBaseline';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'El Chispa',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <CssBaseline />
                <NavBar />
                {children}
            </body>
        </html>
    );
}
